//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TeleoperationVr
{
    [Serializable]
    public class ObjectDataMsg : Message
    {
        public const string k_RosMessageName = "teleoperation_vr/ObjectData";
        public override string RosMessageName => k_RosMessageName;

        //  ObjectData.msg
        public string object_name;
        public double timestamp;
        public Geometry.Vector3Msg position;
        public Geometry.Vector3Msg velocity;

        public ObjectDataMsg()
        {
            this.object_name = "";
            this.timestamp = 0.0;
            this.position = new Geometry.Vector3Msg();
            this.velocity = new Geometry.Vector3Msg();
        }

        public ObjectDataMsg(string object_name, double timestamp, Geometry.Vector3Msg position, Geometry.Vector3Msg velocity)
        {
            this.object_name = object_name;
            this.timestamp = timestamp;
            this.position = position;
            this.velocity = velocity;
        }

        public static ObjectDataMsg Deserialize(MessageDeserializer deserializer) => new ObjectDataMsg(deserializer);

        private ObjectDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.object_name);
            deserializer.Read(out this.timestamp);
            this.position = Geometry.Vector3Msg.Deserialize(deserializer);
            this.velocity = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.object_name);
            serializer.Write(this.timestamp);
            serializer.Write(this.position);
            serializer.Write(this.velocity);
        }

        public override string ToString()
        {
            return "ObjectDataMsg: " +
            "\nobject_name: " + object_name.ToString() +
            "\ntimestamp: " + timestamp.ToString() +
            "\nposition: " + position.ToString() +
            "\nvelocity: " + velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
