//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.VirtualMasterDevice
{
    [Serializable]
    public class Master_dev_stateMsg : Message
    {
        public const string k_RosMessageName = "virtual_master_device/master_dev_state";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseStampedMsg pos;
        public bool button;

        public Master_dev_stateMsg()
        {
            this.pos = new Geometry.PoseStampedMsg();
            this.button = false;
        }

        public Master_dev_stateMsg(Geometry.PoseStampedMsg pos, bool button)
        {
            this.pos = pos;
            this.button = button;
        }

        public static Master_dev_stateMsg Deserialize(MessageDeserializer deserializer) => new Master_dev_stateMsg(deserializer);

        private Master_dev_stateMsg(MessageDeserializer deserializer)
        {
            this.pos = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.button);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
            serializer.Write(this.button);
        }

        public override string ToString()
        {
            return "Master_dev_stateMsg: " +
            "\npos: " + pos.ToString() +
            "\nbutton: " + button.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
